---
- name: Ensure Python is installed
  script: |
    install-py.sh {{ ansible_python_interpreter|default("/usr/bin/python3") }}
  args:
    creates: '{{ ansible_python_interpreter|default("/usr/bin/python3") }}'
  become: yes
