---
- name: "EFS playbook"
  # Este playbook deve ser executado no host local (não nas máquinas remotas)
  hosts: localhost 
  # Não precisamos coletar informações detalhadas da máquina local 
  gather_facts: false
  become: true
  tasks:
  - name: "Create EFS"
    efs:
      state: absent
      name: thais_efs
      region: "us-east-1"
      aws_secret_key: "{{lookup('file', '~/.clap/private/mo833-3.pem') }}"
      aws_access_key: "{{lookup('file', '~/.clap/private/mo833-3.pub') }}"
      #  # Estado -->  Criar
      #  state: "present"
      #  # lookup file retorna o conteudo do arquivo
      #  aws_secret_key: "{{lookup('file', '~/.clap/private/mo833-3.pem') }}"
      #  aws_access_key: "{{lookup('file', '~/.clap/private/mo833-3.pub') }}"
      #  region: "us-east-1"
      #  # Nome do security group
      #  name: "thais_efs"
      #  tags:
      #    name: thais_tag_efs
      #    purpose: file-storage
      #  targets:
      #    - subnet_id: "subnet-bbe700dc"
      #      security_groups: [ "mpi_group_thais" ]
    #  gister: "resultado_da_criacao"

    #- name: "Print creation results dictionary"
    #  debug:
    #    msg: "{{ resultado_da_criacao }}"
