---
#
# Set up SSH host-based authentication
#
- hosts: localhost
  gather_facts: no
  become: no
  tasks:
  - name: Generate an ID rsa if does not exists
    openssh_keypair:
      path: "~/.clap/private/cluster_rsa"
    register: ssh_keys

- hosts: all
  gather_facts: yes
  become: no
  tasks: 
  - name: Copy private SSH KEY
    copy:
      src: ~/.clap/private/cluster_rsa
      dest: ~/.ssh/id_rsa

  - name: Copy public SSH KEY
    copy:
      src: ~/.clap/private/cluster_rsa.pub
      dest: ~/.ssh/id_rsa.pub

  - name: Add rsa-key in authorized_keys
    shell: "cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys"

  - name: Execute chmod 600
    become: true
    shell: "chmod 600 /home/ubuntu/.ssh/id_rsa && chmod 600 /home/ubuntu/.ssh/id_rsa.pub"

  - name: StrictHostKeyChecking not necessary
    shell: "touch ~/.ssh/config && echo 'Host * \n    StrictHostKeyChecking no' >> ~/.ssh/config"
