- name: "Executing script '{{ item }}' (timeout 10min)"
  poll: 15
  async: 600
  script: 
    cmd: "{{ item }}"
    chdir: "{{ exec_dir }}"
  register: script_results
  ignore_errors: yes
  
- name: Save output
  copy:
    content: "{{ script_results.stdout }}"
    dest: "{{ output_dir }}/{{ execution_id }}-{{ item| basename }}.out"

- name: Save error
  copy:
    content: "{{ script_results.stderr }}"
    dest: "{{ output_dir }}/{{ execution_id }}-{{ item| basename }}.err"

- name: Fail if script resulted in errors
  fail:
    msg: "Script {{ item }} failed to execute (returned non-zero code)" 
  when: script_results.rc != 0
