---
- hosts: all
  gather_facts: yes
  vars:
    exec_dir: "{{ execution_dir | default(ansible_env.HOME+'/'+paramount_id) }}"
  tasks:
  - name: Execute install script
    poll: 15
    script: 
      cmd: "{{ script_install }}"
      chdir: "{{ exec_dir }}"
      
