---
- hosts: localhost
  gather_facts: no
  become: no
  tasks:
  - name: Generate an ID rsa if does not exists
    openssh_keypair:
      path: "~/.clap/private/cluster_rsa"

- hosts: all
  gather_facts: yes
  become: no
  vars:
    exec_dir: "{{ execution_dir | default(ansible_env.HOME+paramount_id) }}"
  tasks: 
  - name: Copy private SSH KEY
    copy:
      src: ~/.clap/private/cluster_rsa
      dest: "{{ansible_env.HOME}}/.ssh/id_rsa"

  - name: Copy public SSH KEY
    copy:
      src: ~/.clap/private/cluster_rsa.pub
      dest: "{{ansible_env.HOME}}/.ssh/id_rsa.pub"

  - name: Add rsa-key in authorized_keys
    shell: "cat {{ansible_env.HOME}}/.ssh/id_rsa.pub >> {{ansible_env.HOME}}/.ssh/authorized_keys"

  - name: Execute chmod 600
    become: true
    shell: "chmod 600 {{ansible_env.HOME}}/.ssh/id_rsa && chmod 600 {{ansible_env.HOME}}/.ssh/id_rsa.pub"

  - name: StrictHostKeyChecking not necessary
    shell: "touch {{ansible_env.HOME}}/.ssh/config && echo 'Host * \n    StrictHostKeyChecking no' >> {{ansible_env.HOME}}/.ssh/config"

  # If app dir is defined, we will copy it to remote location
  - block:
    - name: Create the paramount directory
      file: 
        path: "{{ exec_dir }}"
        state: directory
    - name: Copy application files
      synchronize:
        src: "{{ app_dir }}"
        dest: "{{ exec_dir }}"
    when: app_dir is defined
