---
- hosts: master
  gather_facts: yes
  vars:
    exec_dir: "{{ execution_dir | default(ansible_env.HOME+'/'+paramount_id) }}"
  tasks:
  - name: "Executing script '{{ script_to_execute }}'"
    poll: 15
    script: 
      cmd: "{{ script_to_execute }}"
      chdir: "{{ exec_dir }}"
    register: script_results
    ignore_errors: yes
    
  - name: Save output
    copy:
      content: "{{ script_results.stdout }}"
      dest: "{{ output_dir }}/{{ execution_id }}-{{ inventory_hostname }}-{{ script_to_execute| basename }}.out"
    delegate_to: localhost

  - name: Save error
    copy:
      content: "{{ script_results.stderr }}"
      dest: "{{ output_dir }}/{{ execution_id }}-{{ inventory_hostname }}-{{ script_to_execute| basename }}.err"
    delegate_to: localhost

  - name: Fail if script resulted in errors
    fail:
      msg: "Script {{ script_to_execute }} failed to execute (returned non-zero code)" 
    when: script_results.rc != 0
