---
- name: Create EFS mount point
  file: 
    path: "{{ mount_point }}" 
    owner: "{{ mount_owner }}" 
    group: "{{ mount_group }}"
    state: directory 

#- name: Query for EFS availability zone
#  uri: 
#    url: 'http://169.254.169.254/latest/meta-data/placement/availability-zone' 
#    return_content: yes
#  register: _availability_zone

- name: Mount EFS volume
  mount:
    name: "{{ mount_point }}"
    src: "{{ mount_ip }}:"
    fstype: nfs4
    opts: 'nfsvers=4.1'
    state: mounted

- name: Ensure chown on the mounted volume
  file:
    path: "{{ mount_point }}"
    owner: "{{ mount_owner }}"
    group: "{{ mount_group }}"
    mode: "{{ mount_permissions }}"
